// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'55bdb93db4c21d06705fed66e30f57f4212159ddfb1655fd8a411c6bf24ca6fe'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Administrators: {
      readonly CanAddGroup: CodecTypes['pg/bool@1']['output'];
      readonly CanGetRole: CodecTypes['pg/bool@1']['output'];
      readonly CanManageGroup: CodecTypes['pg/bool@1']['output'];
      readonly CanManageLog: CodecTypes['pg/bool@1']['output'];
      readonly CanManageSmode: CodecTypes['pg/bool@1']['output'];
      readonly CanManageUbot: CodecTypes['pg/bool@1']['output'];
      readonly CanPromoteUser: CodecTypes['pg/bool@1']['output'];
      readonly CanStartSmode: CodecTypes['pg/bool@1']['output'];
      readonly CanUseNext: CodecTypes['pg/bool@1']['output'];
      readonly CanUseReset: CodecTypes['pg/bool@1']['output'];
      readonly CanViewLog: CodecTypes['pg/bool@1']['output'];
      readonly IsHighAdmin: CodecTypes['pg/bool@1']['output'];
      readonly Promotor: CodecTypes['pg/text@1']['output'];
      readonly UserId: CodecTypes['pg/text@1']['output'];
    };
    readonly DisabledUserBot: { readonly UserId: CodecTypes['pg/text@1']['output'] };
    readonly Group: {
      readonly GroupId: CodecTypes['pg/text@1']['output'];
      readonly GroupName: CodecTypes['pg/text@1']['output'];
    };
    readonly Userbots: {
      readonly IsActive: CodecTypes['pg/bool@1']['output'];
      readonly SessionString: CodecTypes['pg/text@1']['output'];
      readonly Sort: CodecTypes['pg/int4@1']['output'];
      readonly UserId: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Administrators: {
      readonly CanAddGroup: CodecTypes['pg/bool@1']['input'];
      readonly CanGetRole: CodecTypes['pg/bool@1']['input'];
      readonly CanManageGroup: CodecTypes['pg/bool@1']['input'];
      readonly CanManageLog: CodecTypes['pg/bool@1']['input'];
      readonly CanManageSmode: CodecTypes['pg/bool@1']['input'];
      readonly CanManageUbot: CodecTypes['pg/bool@1']['input'];
      readonly CanPromoteUser: CodecTypes['pg/bool@1']['input'];
      readonly CanStartSmode: CodecTypes['pg/bool@1']['input'];
      readonly CanUseNext: CodecTypes['pg/bool@1']['input'];
      readonly CanUseReset: CodecTypes['pg/bool@1']['input'];
      readonly CanViewLog: CodecTypes['pg/bool@1']['input'];
      readonly IsHighAdmin: CodecTypes['pg/bool@1']['input'];
      readonly Promotor: CodecTypes['pg/text@1']['input'];
      readonly UserId: CodecTypes['pg/text@1']['input'];
    };
    readonly DisabledUserBot: { readonly UserId: CodecTypes['pg/text@1']['input'] };
    readonly Group: {
      readonly GroupId: CodecTypes['pg/text@1']['input'];
      readonly GroupName: CodecTypes['pg/text@1']['input'];
    };
    readonly Userbots: {
      readonly IsActive: CodecTypes['pg/bool@1']['input'];
      readonly SessionString: CodecTypes['pg/text@1']['input'];
      readonly Sort: CodecTypes['pg/int4@1']['input'];
      readonly UserId: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Administrators: {
      readonly CanAddGroup: CodecTypes['pg/bool@1']['output'];
      readonly CanGetRole: CodecTypes['pg/bool@1']['output'];
      readonly CanManageGroup: CodecTypes['pg/bool@1']['output'];
      readonly CanManageLog: CodecTypes['pg/bool@1']['output'];
      readonly CanManageSmode: CodecTypes['pg/bool@1']['output'];
      readonly CanManageUbot: CodecTypes['pg/bool@1']['output'];
      readonly CanPromoteUser: CodecTypes['pg/bool@1']['output'];
      readonly CanStartSmode: CodecTypes['pg/bool@1']['output'];
      readonly CanUseNext: CodecTypes['pg/bool@1']['output'];
      readonly CanUseReset: CodecTypes['pg/bool@1']['output'];
      readonly CanViewLog: CodecTypes['pg/bool@1']['output'];
      readonly IsHighAdmin: CodecTypes['pg/bool@1']['output'];
      readonly Promotor: CodecTypes['pg/text@1']['output'];
      readonly UserId: CodecTypes['pg/text@1']['output'];
    };
    readonly DisabledUserBot: { readonly UserId: CodecTypes['pg/text@1']['output'] };
    readonly Group: {
      readonly GroupId: CodecTypes['pg/text@1']['output'];
      readonly GroupName: CodecTypes['pg/text@1']['output'];
    };
    readonly Userbots: {
      readonly IsActive: CodecTypes['pg/bool@1']['output'];
      readonly SessionString: CodecTypes['pg/text@1']['output'];
      readonly Sort: CodecTypes['pg/int4@1']['output'];
      readonly UserId: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Administrators: {
      readonly CanAddGroup: CodecTypes['pg/bool@1']['input'];
      readonly CanGetRole: CodecTypes['pg/bool@1']['input'];
      readonly CanManageGroup: CodecTypes['pg/bool@1']['input'];
      readonly CanManageLog: CodecTypes['pg/bool@1']['input'];
      readonly CanManageSmode: CodecTypes['pg/bool@1']['input'];
      readonly CanManageUbot: CodecTypes['pg/bool@1']['input'];
      readonly CanPromoteUser: CodecTypes['pg/bool@1']['input'];
      readonly CanStartSmode: CodecTypes['pg/bool@1']['input'];
      readonly CanUseNext: CodecTypes['pg/bool@1']['input'];
      readonly CanUseReset: CodecTypes['pg/bool@1']['input'];
      readonly CanViewLog: CodecTypes['pg/bool@1']['input'];
      readonly IsHighAdmin: CodecTypes['pg/bool@1']['input'];
      readonly Promotor: CodecTypes['pg/text@1']['input'];
      readonly UserId: CodecTypes['pg/text@1']['input'];
    };
    readonly DisabledUserBot: { readonly UserId: CodecTypes['pg/text@1']['input'] };
    readonly Group: {
      readonly GroupId: CodecTypes['pg/text@1']['input'];
      readonly GroupName: CodecTypes['pg/text@1']['input'];
    };
    readonly Userbots: {
      readonly IsActive: CodecTypes['pg/bool@1']['input'];
      readonly SessionString: CodecTypes['pg/text@1']['input'];
      readonly Sort: CodecTypes['pg/int4@1']['input'];
      readonly UserId: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Administrators = {
    CanAddGroup: CodecTypes['pg/bool@1']['output'];
    CanGetRole: CodecTypes['pg/bool@1']['output'];
    CanManageGroup: CodecTypes['pg/bool@1']['output'];
    CanManageLog: CodecTypes['pg/bool@1']['output'];
    CanManageSmode: CodecTypes['pg/bool@1']['output'];
    CanManageUbot: CodecTypes['pg/bool@1']['output'];
    CanPromoteUser: CodecTypes['pg/bool@1']['output'];
    CanStartSmode: CodecTypes['pg/bool@1']['output'];
    CanUseNext: CodecTypes['pg/bool@1']['output'];
    CanUseReset: CodecTypes['pg/bool@1']['output'];
    CanViewLog: CodecTypes['pg/bool@1']['output'];
    IsHighAdmin: CodecTypes['pg/bool@1']['output'];
    Promotor: CodecTypes['pg/text@1']['output'];
    UserId: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_DisabledUserBot = {
    UserId: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Group = {
    GroupId: CodecTypes['pg/text@1']['output'];
    GroupName: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Userbots = {
    IsActive: CodecTypes['pg/bool@1']['output'];
    SessionString: CodecTypes['pg/text@1']['output'];
    Sort: CodecTypes['pg/int4@1']['output'];
    UserId: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    Administrators: Models.public_Administrators;
    DisabledUserBot: Models.public_DisabledUserBot;
    Group: Models.public_Group;
    Userbots: Models.public_Userbots;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Administrators: {
              columns: {
                readonly CanAddGroup: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly CanGetRole: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly CanManageGroup: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly CanManageLog: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly CanManageSmode: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly CanManageUbot: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly CanPromoteUser: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly CanStartSmode: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly CanUseNext: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly CanUseReset: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly CanViewLog: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly IsHighAdmin: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly Promotor: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly UserId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['UserId'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly DisabledUserBot: {
              columns: {
                readonly UserId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['UserId'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Group: {
              columns: {
                readonly GroupId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly GroupName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['GroupId'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Userbots: {
              columns: {
                readonly IsActive: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly SessionString: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly Sort: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly UserId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['UserId'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Administrators: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Administrators';
    };
    readonly DisabledUserBot: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'DisabledUserBot';
    };
    readonly Group: { readonly namespace: 'public' & NamespaceId; readonly model: 'Group' };
    readonly Userbots: { readonly namespace: 'public' & NamespaceId; readonly model: 'Userbots' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Administrators: {
            readonly fields: {
              readonly CanAddGroup: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly CanGetRole: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly CanManageGroup: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly CanManageLog: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly CanManageSmode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly CanManageUbot: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly CanPromoteUser: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly CanStartSmode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly CanUseNext: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly CanUseReset: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly CanViewLog: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly IsHighAdmin: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly Promotor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly UserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Administrators';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly CanAddGroup: { readonly column: 'CanAddGroup' };
                readonly CanGetRole: { readonly column: 'CanGetRole' };
                readonly CanManageGroup: { readonly column: 'CanManageGroup' };
                readonly CanManageLog: { readonly column: 'CanManageLog' };
                readonly CanManageSmode: { readonly column: 'CanManageSmode' };
                readonly CanManageUbot: { readonly column: 'CanManageUbot' };
                readonly CanPromoteUser: { readonly column: 'CanPromoteUser' };
                readonly CanStartSmode: { readonly column: 'CanStartSmode' };
                readonly CanUseNext: { readonly column: 'CanUseNext' };
                readonly CanUseReset: { readonly column: 'CanUseReset' };
                readonly CanViewLog: { readonly column: 'CanViewLog' };
                readonly IsHighAdmin: { readonly column: 'IsHighAdmin' };
                readonly Promotor: { readonly column: 'Promotor' };
                readonly UserId: { readonly column: 'UserId' };
              };
            };
          };
          readonly DisabledUserBot: {
            readonly fields: {
              readonly UserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'DisabledUserBot';
              readonly namespaceId: 'public';
              readonly fields: { readonly UserId: { readonly column: 'UserId' } };
            };
          };
          readonly Group: {
            readonly fields: {
              readonly GroupId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly GroupName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Group';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly GroupId: { readonly column: 'GroupId' };
                readonly GroupName: { readonly column: 'GroupName' };
              };
            };
          };
          readonly Userbots: {
            readonly fields: {
              readonly IsActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly SessionString: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly Sort: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly UserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Userbots';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly IsActive: { readonly column: 'IsActive' };
                readonly SessionString: { readonly column: 'SessionString' };
                readonly Sort: { readonly column: 'Sort' };
                readonly UserId: { readonly column: 'UserId' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
