# fly.toml app configuration file generated for ucbibvbjusbdvuvbapvdnanhvsuobvounsulonbodehnv on 2026-10-06T06:20:06Z
#
# See https://docs.fly.io/reference/configuration for information about how to use this file.
#

app = "ucbibvbjusbdvuvbapvdnanhvsuobvounsulonbodehnv"
primary_region = 'sin'

[deploy]
  strategy = 'immediate'

[env]
PORT = "3000"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 3000
min_machines_running = 1
  checks = [{ grace_period = '10s', interval = '30s', method = 'GET', path = '/ping', timeout = '5s' }]

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory = '512mb'
  memory_mb = 512
  processes = ['app']
  size = 'shared-cpu-2x'

[[restart]]
  policy = "always"